layout_spectrum: 0.6329031
color:
  saturation: 0.830827
  brandStrength: 0.8171851
  lightness: 0.4441461
  rhythmicContrast: 0.5612245
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.8899648
name: Ruigendyk
